### ISSUE TITLE
[PE-D] No sample contacts are shown 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W09-1/tp#134]
![Screenshot 2022-04-01 at 2.16.54 PM.png](https://raw.githubusercontent.com/tonishka/ped/main/files/c81b33be-ad0a-4013-80b2-011748960602.png)

I don't see the GUI similar to one in the UG when I first open up the app.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tonishka/ped#1

**Comment by vishandi** [comment]
insufficient description. doesn't give enough information to replicate the said issue.
