### ISSUE TITLE
Include your own profile photo

### ISSUE THREAD

**Issue by hanqinilnix** [AY2122S2-CS2103T-W09-1/tp#3]
Include your own profile photo

**Comment by vishandi** [comment]
Update: vishandi's done via [this](https://github.com/AY2122S2-CS2103T-W09-1/tp/pull/6) pr.

**Comment by vishandi** [comment]
- [ ] tyanhan
- [ ] markbiju
- [ ] hanqinilnix
- [ ] vishandi
